SUBROUTINE SLORXY(VARI,NITER,ERROR,NIM,NJM,AE,AW,AN,AS,CAS,SO,OMGA)

   INCLUDE 'PARAMETER.inc'

 DIMENSION VARI(NX,NY)
 DIMENSION BAT(NX),DAT(NX)
 DIMENSION AE(NX,NY),AW(NX,NY),AN(NX,NY),AS(NX,NY),CAS(NX,NY),SO(NX,NY)


DO L=1, NITER

  DO I=2,NIM
    DO J=2,NJM
        SOUCE =SO(I,J)+AE(I,J)*VARI(I+1,J)+AW(I,J)*VARI(I-1,J)
       IF(J == 2)THEN 
        BAT(J)=AN(I,J)/CAS(I,J)
        DAT(J)=(AS(I,J)*VARI(I,J-1)+SOUCE)/CAS(I,J)
       ELSE
        BAT(J)=AN(I,J)/(CAS(I,J)-AS(I,J)*BAT(J-1))
        DAT(J)=(AS(I,J)*DAT(J-1)+SOUCE)/(CAS(I,J)-AS(I,J)*BAT(J-1))
       ENDIF
    ENDDO
    DO J=NJM,2,-1
        VARI(I,J)=VARI(I,J)+OMGA*(BAT(J)*VARI(I,J+1)+DAT(J)-VARI(I,J))
    ENDDO
  ENDDO

  DO J=2,NJM
    DO I=2,NIM
      SOUCE=SO(I,J)+AN(I,J)*VARI(I,J+1)+AS(I,J)*VARI(I,J-1)
     IF(I == 2) THEN
      BAT(I)=AE(I,J)/CAS(I,J)
      DAT(I)=(AW(I,J)*VARI(I-1,J)+SOUCE)/CAS(I,J)
     ELSE
      BAT(I)=AE(I,J)/(CAS(I,J)-AW(I,J)*BAT(I-1))
      DAT(I)=(AW(I,J)*DAT(I-1)+SOUCE)/(CAS(I,J)-AW(I,J)*BAT(I-1))
     ENDIF
    ENDDO
    DO I=NIM,2,-1
        VARI(I,J)=VARI(I,J)+OMGA*(BAT(I)*VARI(I+1,J)+DAT(I)-VARI(I,J))
    ENDDO
  ENDDO

  ERROR = 0.00
  DO J=2,NJM
  DO I=2,NIM
    VARIMAX=SO(I,J)+AN(I,J)*VARI(I,J+1)+AS(I,J)*VARI(I,J-1)            &
         +AE(I,J)*VARI(I+1,J)+AW(I,J)*VARI(I-1,J)-VARI(I,J)*CAS(I,J)
    VARIMAX=ABS(VARIMAX)
    IF(VARIMAX.GE.ERROR)   ERROR=VARIMAX
  ENDDO
  ENDDO

ENDDO

RETURN
END